export const questionBank = {
    "0": "When was the last time you tried something new?",
    "1": "Who do you sometimes compare yourself to?",
    "2": "What's the most sensible thing you've ever heard someone say?",
    "3": "What gets you excited about life?",
    "4": "What life lesson did you learn the hard way?",
    "5": "What do you wish you spent more time doing five years ago?",
    "6": "Do you ask enough questions or do you settle for what you know?",
    "7": "Who do you love and what are you doing about it?",
    "8": "What's a belief that you hold with which many people disagree?",
    "9": "What can you do today that you were not capable of a year ago?",
    "10": "Do you think crying is a sign of weakness or strength?",
    "11": "What would you do differently if you knew nobody would judge you?",
    "12": "Do you celebrate the things you do have?",
    "13": "What is the difference between living and existing?",
    "14": "If not now, then when?",
    "15": "Have you done anything lately worth remembering?",
    "16": "What does your joy look like today?",
    "17": "Is it possible to lie without saying a word?",
    "18": "If you had a friend who spoke to you in the same way that you sometimes speak to yourself, how long would you allow this person to be your friend?",
    "19": "Which activities make you lose track of time?",
    "20": "If you had to teach something, what would you teach?",
    "21": "What would you regret not fully doing, being or having in your life?",
    "22": "Are you holding onto something that you need to let go of?",
    "23": "When you are 80-years-old, what will matter to you the most?",
    "24": "When is it time to stop calculating risk and rewards and just do what you know is right?",
    "25": "How old would you be if you didn't know how old you are?",
    "26": "Would you break the law to save a loved one?",
    "27": "What makes you smile?",
    "28": "When it's all said and done, will you have said more than you've done?",
    "29": "If you had the opportunity to get a message across to a large group of people, what would your message be?",
    "30": "If the average human lifespan was 40 years, how would you live your life differently?",
    "31": "What do we all have in common besides our genes that makes us human?",
    "32": "If you could choose one book as a mandatory read for all high school students, which book would you choose?",
    "33": "Would you rather have less work or more work you actually enjoy doing?",
    "34": "What is important enough to go to war over?",
    "35": "Which is worse, failing or never trying?",
    "36": "When was the last time you listened to the sound of your own breathing?",
    "37": "What's something you know you do differently than most people?",
    "38": "What does 'The American Dream' mean to you?",
    "39": "Would you rather be a worried genius or a joyful simpleton?",
    "40": "If you could instill one piece of advice in a newborn baby's mind, what advice would you give?",
    "41": "What is the most desirable trait another person can possess?",
    "42": "What are you most grateful for?",
    "43": "Is stealing to feed a starving child wrong?",
    "44": "What do you want most?",
    "45": "Are you more worried about doing things right, or doing the right things?",
    "46": "What has life taught you recently?",
    "47": "What is the one thing you would most like to change about the world?",
    "48": "Where do you find inspiration?",
    "49": "Can you describe your life in a six word sentence?",
    "50": "If we learn from our mistakes, why are we always so afraid to make a mistake?",
    "51": "What impact do you want to leave on the world?",
    "52": "What is the most defining moment of your life thus far?",
    "53": "In the haste of your daily life, what are you not seeing?",
    "54": "If life is so short, why do we do so many things we don't like and like so many things we don't do?",
    "55": "What lifts your spirits when life gets you down?",
    "56": "Have you ever regretted something you did not say or do?",
    "57": "Has your greatest fear ever come true?",
    "58": "Why do we think of others the most when they're gone?",
    "59": "What is your most beloved childhood memory?",
    "60": "Is it more important to love or be loved?",
    "61": "If it all came back around to you, would it help you or hurt you?",
    "62": "If you had the chance to go back in time and change one thing would you do it?",
    "63": "If a doctor gave you five years to live, what would you try to accomplish?",
    "64": "What is the difference between falling in love and being in love?",
    "65": "Who do you think stands between you and happiness?",
    "66": "What is the difference between innocence and ignorance?",
    "67": "What is the simplest truth you can express in words?",
    "68": "What gives your life meaning?",
    "69": "Can there be happiness without sadness? Pleasure without pain? Peace without war?",
    "70": "What's the one thing you'd like others to remember about you at the end of your life?",
    "71": "Is there such a thing as perfect?",
    "72": "To what degree have you actually controlled the course your life has taken?",
    "73": "What does it mean to be human?",
    "74": "If you looked into the heart of your enemy, what do you think you would find that is different from what is in your own heart?",
    "75": "What do you love most about yourself?",
    "76": "Where would you most like to go and why?",
    "77": "Is it more important to do what you love or to love what you are doing?",
    "78": "What do you imagine yourself doing ten years from now?",
    "79": "What small act of kindness were you once shown that you will never forget?",
    "80": "What is your happiest childhood memory? What makes it so special?",
    "81": "Do you own your things or do your things own you?",
    "82": "Would you rather lose all of your old memories or never be able to make new ones?",
    "83": "How do you deal with someone in a position of power who wants you to fail?",
    "84": "What do you have that you cannot live without?",
    "85": "When you close your eyes what do you see?",
    "86": "What sustains you on a daily basis?",
    "87": "What are your top five personal values?",
    "88": "Why must you love someone enough to let them go?",
    "89": "Do you ever celebrate the green lights?",
    "90": "What personal prisons have you built out of fears?",
    "91": "What one thing have you not done that you really want to do?",
    "92": "Why are you, you?",
    "93": "If you haven't achieved it yet what do you have to lose?",
    "94": "What three words would you use to describe the last three months of your life?",
    "95": "Is it ever right to do the wrong thing? Is it ever wrong to do the right thing?",
    "96": "How would you describe 'freedom' in your own words?",
    "97": "What is the most important thing you could do right now in your personal life?",
    "98": "If you could ask one person, alive or dead, only one question, who would you ask and what would you ask?",
    "99": "If happiness was the national currency, what kind of work would make you rich?",
    "100": "What is your number one goal for the next six months?",
    "101": "Would you ever give up your life to save someone else?",
    "102": "Are you happy with yourself?",
    "103": "What is the meaning of 'peace' to you?",
    "104": "What are three moral rules you will never break?",
    "105": "What does it mean to allow another person to truly love you?",
    "106": "Who or what do you think of when you think of love?",
    "107": "If your life was a novel, what would be the title and how would your story end?",
    "108": "What would you not give up for $1,000,000 in cash?",
    "109": "When do you feel most like yourself?",
    "110": "When you help someone do you ever think, “What's in it for me?”",
    "111": "What is your greatest challenge?",
    "112": "How do you know when it's time to continue holding on or time to let go?",
    "113": "How do you define success?",
    "114": "If someone could tell you the exact day and time you are going to die, would you want them to tell you?",
    "115": "If I could grant you one wish what would you wish for?",
    "116": "What have you read online recently that inspired you?",
    "117": "Why do religions that advocate unity divide the human race?",
    "118": "If you could live one day of your life over again, what day would you choose?",
    "119": "What can money not buy?",
    "120": "If you left this life tomorrow, how would you be remembered?",
    "121": "Beyond the titles that others have given you, who are you?",
    "122": "If you could live the next 24 hours and then erase it and start over just once, what would you do?",
    "123": "Is it possible to know the truth without challenging it first?",
    "124": "What word best describes the way you've spent the last month of your life?",
    "125": "What makes everyone smile?",
    "126": "What do you owe yourself?",
    "127": "What would your 'priceless' Mastercard-style commercial be?",
    "128": "Can you think of a time when impossible became possible?",
    "129": "Why do you matter?",
    "130": "How have you changed in the last five years?",
    "131": "What are you sure of in your life?",
    "132": "When you think of 'home,' what, specifically, do you think of?",
    "133": "What's the difference between settling for things and accepting the way things are?",
    "134": "How many of your friends would you trust with your life?",
    "135": "What's your definition of heaven?",
    "136": "What is your most prized possession?",
    "137": "How would you describe yourself in one sentence?",
    "138": "What stands between you and happiness?",
    "139": "What makes a person beautiful?",
    "140": "Is there ever a time when giving up makes sense?",
    "141": "What makes you proud?",
    "142": "How do you find the strength to do what you know in your heart is right?",
    "143": "Where do you find peace?",
    "144": "When have you worked hard and loved every minute of it?",
    "145": "How short would your life have to be before you would start living differently today?",
    "146": "Is it better to have loved and lost or to have never loved at all?",
    "147": "What would you do if you made a mistake and somebody died?",
    "148": "Who do you trust and why?",
    "149": "If you were forced to eliminate every physical possession from your life with the exception of what could fit into a single backpack, what would you put in it?",
    "150": "When does silence convey more meaning than words?",
    "151": "How do you spend the majority of your free time?",
    "152": "Who do you think of first when you think of 'success?'",
    "153": "What did you want to be when you grew up?",
    "154": "How will today matter in five years from now?",
    "155": "How have you helped someone else recently?",
    "156": "What is your greatest skill?",
    "157": "Do you see to believe or believe to see?",
    "158": "How are you pursuing your dreams right now?",
    "159": "What's the next big step you need to take?",
    "160": "If today was the last day of your life, would you want to do what you are about to do today?",
    "161": "If today was the last day of your life, who would you call and what would you tell them?",
    "162": "Who do you dream about?",
    "163": "What do you have trouble seeing clearly in your mind?",
    "164": "What are you looking forward to?",
    "165": "What is the number one thing you want to accomplish before you die?",
    "166": "When is love a weakness?",
    "167": "What has been the most terrifying moment of your life thus far?",
    "168": "Who is the strongest person you know?",
    "169": "If you could take a single photograph of your life, what would it look like?",
    "170": "Is the reward worth the risk?",
    "171": "For you personally, what makes today worth living?",
    "172": "What have you done in the last year that makes you proud?",
    "173": "What did you learn recently that changed the way you live?",
    "174": "What is your fondest memory from the past three years?",
    "175": "What are the primary components of a happy life?",
    "176": "How would the world be different if you were never born?",
    "177": "What is your favorite song and why?",
    "178": "With the resources you have right now, what can you do to bring yourself closer to your goal?",
    "179": "What are your top three priorities?",
    "180": "Why do we idolize sports players?",
    "181": "What is the nicest thing someone has ever done for you?",
    "182": "What do you see when you look into the future?",
    "183": "What makes you angry? Why?",
    "184": "What is the most valuable life lesson you learned from your parents?",
    "185": "What does love feel like?",
    "186": "What are your favorite simple pleasures?",
    "187": "If you could go back in time and tell a younger version of yourself one thing, what would you tell?",
    "188": "What do you do to deliberately impress others?",
    "189": "What will you never do?",
    "190": "Excluding romantic relationships, who do you love?",
    "191": "What is your earliest childhood memory?",
    "192": "What book has had the greatest influence on your life?",
    "193": "What three questions do you wish you knew the answers to?",
    "194": "What is the greatest peer pressure you've ever felt?",
    "195": "What's the biggest lie you once believed was true?",
    "196": "In your lifetime, what have you done that hurt someone else?",
    "197": "What's the best part of growing older?",
    "198": "What's been on your mind most lately?",
    "199": "What do you think is worth waiting for?",
    "200": "What chances do you wish you had taken?",
    "201": "Where else would you like to live? Why?",
    "202": "What motivates you to go to work each day?",
    "203": "What do you wish you had done differently?",
    "204": "What is your greatest strength and your greatest weakness?",
    "205": "When was the last time you lied? What did you lie about?",
    "206": "What made you smile this week?",
    "207": "What do you do with the majority of your money?",
    "208": "What motivates you to be your best?",
    "209": "When was the last time you lost your temper? About what?",
    "210": "What will you never give up on?",
    "211": "When you look into the past, what do you miss the most?",
    "212": "How would you describe the past year of your life in one sentence?",
    "213": "What is the most spontaneous thing you've ever done?",
    "214": "What makes you uncomfortable?",
    "215": "If you had to move 3000 miles away, what one thing would you miss the most?",
    "216": "What worries you about the future?",
    "217": "What one 'need' and one 'want' will you strive to achieve in the next twelve months?",
    "218": "What life lessons did you have to experience firsthand before you fully understood them?",
    "219": "Do you like the city or town you live in? Why or why not?",
    "220": "What's the best part of being you?",
    "221": "When you look back over the past month, what single moment stands out?",
    "222": "What do you do to relieve stress?",
    "223": "What is your happiest memory?",
    "224": "What is your saddest memory?",
    "225": "What would you like to change?",
    "226": "How many people do you love?",
    "227": "What's the best decision you've ever made?",
    "228": "What's your favorite true story that you enjoy sharing with others?",
    "229": "Right now, at this moment, what do you want most?",
    "230": "What are you waiting for? How are you writing your life's story?",
    "231": "What makes love last?",
    "232": "What good comes from suffering?",
    "233": "What's the most important lesson you've learned in the last year?",
    "234": "Based on you current daily actions and routines, where would you expect to be in five years?",
    "235": "What was your last major accomplishment?",
    "236": "Through all of life's twists and turns who has been there for you?",
    "237": "What or who has been distracting you?",
    "238": "What are you looking forward to in the upcoming week?",
    "239": "Who is your mentor and what have you learned from them?",
    "240": "What are you uncertain about?",
    "241": "What do you think about when you lie awake in bed?",
    "242": "What's something most people don't know about you?",
    "243": "When you have a random hour of free time, what do you usually do?",
    "244": "What makes you weird?",
    "245": "If you could relive yesterday what would you do differently?",
    "246": "What do you do over and over again that you hate doing?",
    "247": "Would you rather your child be less attractive and extremely intelligent or extremely attractive and less intelligent?",
    "248": "What white lies do you often tell?",
    "249": "What is the biggest change you have made in your life in the last year?",
    "250": "What do you understand today about your life that you did not understand a year ago?",
    "251": "Whose life have you had the greatest impact on?",
    "252": "What did life teach you yesterday?",
    "253": "Who impresses you?",
    "254": "What have you done that you are not proud of?",
    "255": "When should you reveal a secret that you promised you wouldn't reveal?",
    "256": "How would you spend your ideal day?",
    "257": "What is the one primary quality you look for in a significant other?",
    "258": "What do you admire most about your mother and father?",
    "259": "What is the best advice you have ever received?",
    "260": "If you could live forever, would you want to? Why?",
    "261": "If you had to be someone else for one day, who would you be and why?",
    "262": "What positive changes have you made in your life recently?",
    "263": "Who makes you feel good about yourself?",
    "264": "What is your biggest regret?",
    "265": "Which one of your responsibilities do you wish you could get rid of?",
    "266": "What's something you don't like to do that you are still really good at?",
    "267": "What type of person angers you the most?",
    "268": "What is missing in your life?",
    "269": "What is your most striking physical attribute?",
    "270": "What has fear of failure stopped you from doing?",
    "271": "Who would you like to please the most?",
    "272": "If you could go back in time and change things, what would you change about the week that just passed?",
    "273": "When you meet someone for the very first time what do you want them to think about you?",
    "274": "Who would you like to forgive?",
    "275": "At what point during the last five years have you felt lost and alone?",
    "276": "What is one opportunity you believe you missed out on when you were younger?",
    "277": "What do you want more of in your life?",
    "278": "What do you want less of in your life?",
    "279": "Who depends on you?",
    "280": "Who has had the greatest impact on your life?",
    "281": "Are you happy with where you are in your life? Why?",
    "282": "In one year from today, how do you think your life will be different?",
    "283": "How have you sabotaged yourself in the past five years?",
    "284": "Other than money, what else have you gained from your current job?",
    "285": "Whom do you secretly envy? Why?",
    "286": "In twenty years, what do you want to remember?",
    "287": "What are you most excited about in your life right now - today?",
    "288": "What experience from this past year do you appreciate the most?",
    "289": "What is the most enjoyable thing your family has done together in the last three years?",
    "290": "How many hours of television do you watch in a week? A month? A year?",
    "291": "What is the biggest obstacle that stands in your way right now?",
    "292": "What do you sometimes pretend you understand that you really don't?",
    "293": "What do you like most about your job? What do you dislike most about your job?",
    "294": "What's something new you recently learned about yourself?",
    "295": "In one sentence, how would you describe your relationship with your mother?",
    "296": "What was the most defining moment in your life during this past year?",
    "297": "What's the number one change you need to make in your life in the next twelve months?",
    "298": "What makes you feel secure?",
    "299": "What is your favorite sound?",
    "300": "What are the top three qualities you look for in a friend?",
    "301": "What simple gesture have you recently witnessed that renewed your hope in humanity?",
    "302": "What is your favorite smell?",
    "303": "What recent memory makes you smile the most?",
    "304": "In one word, how would you describe your childhood?",
    "305": "What celebrities do you admire? Why?",
    "306": "What is the number one motivator in your life right now?",
    "307": "What music do you listen to to lift your spirits when you're feeling down?",
    "308": "If I gave you $1000 and told you that you had to spend it today, what would you buy?",
    "309": "What was the last thing that made you laugh out loud?",
    "310": "What is your biggest pet peeve?",
    "311": "Who was the last person you said “I love you” to?",
    "312": "What is your biggest phobia?",
    "313": "What are some recent compliments you've received?",
    "314": "How many friends do you have in real life that you talk to regularly?",
    "315": "How much money per month is enough for you to live comfortably?",
    "316": "When was your first impression of someone totally wrong?",
    "317": "How many hours a week do you spend online?",
    "318": "What do you love to do?",
    "319": "What specific character trait do you want to be known for?",
    "320": "Are you more like your mom or your dad? In what way?",
    "321": "What is the number one quality that makes someone a good leader?",
    "322": "What bad habits do you want to break?",
    "323": "What is your favorite place on Earth?",
    "324": "What do you love to practice?",
    "325": "What questions do you often ask yourself?",
    "326": "What are you an expert at?",
    "327": "How would an extra $1000 a month change your life?",
    "328": "What things in life should always be free?",
    "329": "What is your favorite time of the year?",
    "330": "What is something you have always wanted since you were a kid?",
    "331": "What is the most recent dream you remember having while sleeping?",
    "332": "What confuses you?",
    "333": "In what way are you your own worst enemy?",
    "334": "When did you not speak up when you should have?",
    "335": "What is your favorite quote?",
    "336": "What is your favorite fictional story? (novel, movie, fairytale, etc.)",
    "337": "Where or who do you turn to when you need good advice?",
    "338": "What artistic medium do you use to express yourself?",
    "339": "Who or what is the greatest enemy of mankind?",
    "340": "What's something you wish you had done earlier in life?",
    "341": "What is the closest you have ever come to fearing for your life?",
    "342": "How do you deal with isolation and loneliness?",
    "343": "What do you know well enough to teach to others?",
    "344": "What's a quick decision you once made that changed your life?",
    "345": "What have you lost interest in recently?",
    "346": "What makes life easier?",
    "347": "What was the last thing you furiously argued about with someone?",
    "348": "What job would you never do no matter how much it paid?",
    "349": "What is the number one solution to healing the world?",
    "350": "What could society do without?",
    "351": "What stresses you out?",
    "352": "Now that it's behind you, what did you do last week that was memorable?",
    "353": "Where do you spend most of your time while you're awake?",
    "354": "What makes someone a hero?",
    "355": "When in your life have you been a victim of stereotyping?",
    "356": "When was the last time you felt lucky?",
    "357": "When did you first realize that life is short?",
    "358": "What is the most insensitive thing a person can do?",
    "359": "What can someone do to grab your attention?",
    "360": "What do you usually think about on your drive home from work?",
    "361": "What's one downside of the modern day world?",
    "362": "What simple fact do you wish more people understood?",
    "363": "If you could do it all over again, would you change anything?",
    "364": "How would you describe your future in three words?"
}